# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  openjdk-install: cloudesire/openjdk-install@1.2.3

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/

    steps:
      - openjdk-install/openjdk:
          version: 11
      - run: rm -rf .openjdk_version
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - save_cache:
          paths:
            - ~/.m2
            - .autoconf
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: ./mvnw clean install
      - run: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Analyze on SonarCloud
          command: cd rudder && ./mvnw sonar:sonar && cd ..

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud